# Generated by Django 4.2.7 on 2023-11-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='accountNumber',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
