# Generated by Django 4.2.7 on 2023-11-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accountNumber',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
