# Generated by Django 4.2.7 on 2023-11-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_profile_accountnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkprofile',
            name='capacity',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
